# Generated by Django 2.1 on 2018-08-03 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0002_auto_20180803_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='opinion.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='opinion.Item'),
            preserve_default=False,
        ),
    ]
