# Generated by Django 2.1 on 2018-08-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0003_auto_20180803_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinion',
            options={'ordering': ('publish_date',)},
        ),
    ]
