# Generated by Django 2.1 on 2018-08-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0004_auto_20180804_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type_text',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('', 'Select type')], max_length=7),
        ),
    ]
