# Generated by Django 2.1 on 2018-08-04 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0006_auto_20180804_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='opinion.Category'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='opinion.Category'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='opinion.Item'),
        ),
    ]
