# Generated by Django 2.1 on 2018-08-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0007_auto_20180804_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='opinions_number',
            field=models.IntegerField(default=0),
        ),
    ]
